site_name: OLC Redmine Automator
site_url: https://olc-bioinformatics.github.io/redmine-docs
site_description: Instructions for OLC Redmine Usage
repo_url: https://github.com/OLC-LOC-Bioinformatics/OLCRedmineAutomator
theme: readthedocs

nav:
- Home: 'index.md'
- Getting Started: 'getting_started.md'
- Data:
    - 'External Retrieve': 'data/external_retrieve.md'
    - 'Report Retrieve': 'data/report_retrieve.md'
    - 'SRA Upload': 'data/sra_upload.md'
- Analysis:
    - 'AMRsummary': 'analysis/amrsummary.md'
    - 'AutoCLARK': 'analysis/autoclark.md'
    - 'bcgTree': 'analysis/bcgtree.md'
    - 'CARD-RGI (AMR)': 'analysis/cardrgi.md'
    - 'ConFindr': 'analysis/confindr.md'
    - 'COWSNPhR': 'analysis/cowsnphr.md'
    - 'CloseRelatives': 'analysis/closerelatives.md'
    - 'eCGF': 'analysis/eCGF.md'
    - 'ECTyper': 'analysis/ectyper.md'
    - 'DiversiTree': 'analysis/diversitree.md'
    - 'dRep-ANI': 'analysis/drep.md'
    - 'GeneSeekr': 'analysis/geneseekr.md'
    - 'GWAS-pyseer': 'analysis/pyseer.md'
    - 'IntiminTyper': 'analysis/intimintyper.md'
    - 'KMA - Resistance Detection': 'analysis/kma.md'
    - 'Mashtree': 'analysis/mashtree.md'
    - 'MobSuite': 'analysis/mobsuite.md'
    - 'NearTree': 'analysis/neartree.md'
    - 'PlasmidBorneIdentity': 'analysis/plasmidborneidentity.md'
    - 'PointFinder': 'analysis/pointfinder.md'
    - 'PrimerFinder': 'analysis/primerfinder.md'
    - 'Prokka': 'analysis/prokka.md'
    - 'PSORTb': 'analysis/psortb.md'
    - 'ResFinder': 'analysis/resfinder.md'
    - 'Roary': 'analysis/roary.md'
    - 'SequenceExtractor': 'analysis/sequence_extractor.md'
    - 'sipprverse': 'analysis/sipprverse.md'
    - 'SNVPhyl': 'analysis/snvphyl.md'
    - 'staramr': 'analysis/staramr.md'
    - 'StrainMash': 'analysis/strainmash.md'
    - 'WGS Assembly': 'analysis/wgsassembly.md'
- Internal Use:
    - 'Merge': 'internal_only/merge.md'
- Troubleshooting: 'troubleshooting.md'
- Tutorials: 
    - 'Create Environment': 'tutorials/create_environment.md'
    - 'Create Pages': 'tutorials/create_pages.md'
    - 'Edit Pages': 'tutorials/edit_pages.md'
    - 'Publish Changes': 'tutorials/publish_changes.md'
    

