site_name: OLC Redmine Automator
site_url: https://olc-bioinformatics.github.io/redmine-docs
site_description: Instructions for OLC Redmine Usage
repo_url: https://github.com/forestdussault/OLCRedmineAutomator
theme: flatly

pages:
- Home: 'index.md'
- Getting Started: 'getting_started.md'
- Data:
    - 'External Retrieve': 'data/external_retrieve.md'
    - 'Report Retrieve': 'data/report_retrieve.md'
- Analysis:
    - 'AutoCLARK': 'analysis/autoclark.md'
    - 'ConFindr': 'analysis/confindr.md'
    - 'DiversiTree': 'analysis/diversitree.md'
    - 'MobSuite': 'analysis/mobsuite.md'
    - 'NearTree': 'analysis/neartree.md'
    - 'PointFinder': 'analysis/pointfinder.md'
    - 'ResFinder': 'analysis/resfinder.md'
    - 'SNVPhyl': 'analysis/snvphyl.md'
    - 'StrainMash': 'analysis/strainmash.md'
    - 'WGS Assembly': 'analysis/wgsassembly.md'
- Troubleshooting: 'troubleshooting.md'

