site_name: OLC Redmine Automator
site_url: https://olc-bioinformatics.github.io/redmine-docs
site_description: Instructions for OLC Redmine Usage
#repo_url: https://github.com/forestdussault/OLCRedmineAutomator
theme: flatly

pages:
- Home: 'index.md'
- Getting Started: 'getting_started.md'
- Data:
    - 'External Retrieve': 'data/external_retrieve.md'
    - 'Report Retrieve': 'data/report_retrieve.md'
    - 'SRA Upload': 'data/sra_upload.md'
- Analysis:
    - 'AMRsummary': 'analysis/amrsummary.md'
    - 'AutoCLARK': 'analysis/autoclark.md'
    - 'ConFindr': 'analysis/confindr.md'
    - 'COWSNPhR': 'analysis/cowsnphr.md'
    - 'CloseRelatives': 'analysis/closerelatives.md'
    - 'DiversiTree': 'analysis/diversitree.md'
    - 'GeneSeekr': 'analysis/geneseekr.md'
    - 'MobSuite': 'analysis/mobsuite.md'
    - 'NearTree': 'analysis/neartree.md'
    - 'PlasmidBorneIdentity': 'analysis/plasmidborneidentity.md'
    - 'PointFinder': 'analysis/pointfinder.md'
    - 'Prokka': 'analysis/prokka.md'
    - 'ResFinder': 'analysis/resfinder.md'
    - 'sipprverse': 'analysis/sipprverse.md'
    - 'SNVPhyl': 'analysis/snvphyl.md'
    - 'staramr': 'analysis/staramr.md'
    - 'StrainMash': 'analysis/strainmash.md'
    - 'WGS Assembly': 'analysis/wgsassembly.md'
- Internal Use:
    - 'Merge': 'internal_only/merge.md'
- Troubleshooting: 'troubleshooting.md'

